# syntax=docker/dockerfile:1
FROM pytorch/pytorch:2.10.0-cuda12.8-cudnn9-runtime

ENV PYTHONUNBUFFERED=1
ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1
ENV UV_PROJECT_ENVIRONMENT=/.venv

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /

COPY pyproject.toml uv.lock /
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

ENV PATH="/.venv/bin:$PATH"

RUN python -m spacy download en_core_web_md

COPY . /.

ENV PYTHONPATH=/

# Using ENTRYPOINT allows us to pass args with `docker run`
# ENTRYPOINT ["python", "/src/sent_spans/train.py"]

# For now we'll manually start training, so just sleep here
CMD ["sleep", "infinity"]