[project]
name = "docbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backoff>=2.2.1",
    "boto3==1.*",
    "datasets>=4.8.5",
    "jupyter>=1.1.1",
    "langdetect>=1.0.9",
    "pandas==2.*",
    "peft>=0.19.1",
    "psycopg2-binary>=2.9.12",
    "pytest>=9.0.3",
    "scikit-learn==1.8.*",
    "seaborn>=0.13.2",
    "spacy==3.*",
    "sqlalchemy>=2.0.49",
    "textacy>=0.13.0",
    "torch==2.10.*",
    "tqdm>=4.67.3",
    "transformers==4.*",
    "wandb>=0.26.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]
infer = [
    "backoff>=2.2.1",
    "boto3==1.*",
    "langdetect>=1.0.9",
    "pandas==2.*",
    "peft>=0.19.1",
    "protobuf>=7.34.1",
    "requests>=2.33.1",
    "scikit-learn==1.8.*",
    "seaborn>=0.13.2",
    "spacy==3.*",
    "sqlalchemy>=2.0.49",
    "textacy>=0.13.0",
    "torch==2.10.*",
    "tqdm>=4.67.3",
    "transformers==4.*",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "E402",     # Module level import not at top of cell
]

[tool.ruff.format]
# Prevent trailing commas from forcing parameters onto new lines
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
# Prevent isort from splitting imports on trailing commas
split-on-trailing-comma = false
